version: '2'
services:
  master:
    image:
      willian:pdi-server
    ports:
      - "8181:8181"
      - "40000-40010"
    environment:
      - PDI_RELEASE=9.1
      - PDI_VERSION=9.1.0.0-324
      - CARTE_PORT=8181
      - CARTE_IS_MASTER=Y
      - CARTE_INCLUDE_MASTERS=N
  slave:
    image:
      willian:pdi-server
    ports:
      - "8182"
      - "40000-40010"
    environment:
      - PDI_RELEASE=9.1
      - PDI_VERSION=9.1.0.0-324
      - CARTE_PORT=8182
      - CARTE_IS_MASTER=N
      - CARTE_INCLUDE_MASTERS=Y
      - CARTE_MASTER_HOSTNAME=master
      - CARTE_MASTER_PORT=8181
    links:
      - master
